// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGUeX99vAghgczy_vtGjiN8VCuFxxyj0c',
    appId: '1:920129677321:android:19418e22e7ee739a8ef0d8',
    messagingSenderId: '920129677321',
    projectId: 'skinsafeapp-fdcdb',
    storageBucket: 'skinsafeapp-fdcdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9f8bgF8jlh4I9MzUECmhiPp52sQsb30k',
    appId: '1:920129677321:ios:e67edf02ee7933de8ef0d8',
    messagingSenderId: '920129677321',
    projectId: 'skinsafeapp-fdcdb',
    storageBucket: 'skinsafeapp-fdcdb.firebasestorage.app',
    iosBundleId: 'com.example.skinSafeApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ-HE91GT6mfXQMucZuJB6isrRmEY_Kz8',
    appId: '1:920129677321:web:c1136d12a6b5d29b8ef0d8',
    messagingSenderId: '920129677321',
    projectId: 'skinsafeapp-fdcdb',
    authDomain: 'skinsafeapp-fdcdb.firebaseapp.com',
    storageBucket: 'skinsafeapp-fdcdb.firebasestorage.app',
  );

}